
on: 
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      env:
        description: 'test'     
        required: true
        default: 'test'
jobs:
  do-something:
    
    strategy:
      matrix:
        node: ${{inputs.env}}
    runs-on: ubuntu-latest
    environment: ${{matrix.node}}
    steps:
      - uses: actions/checkout@v2
      - uses: ./actions/
      - name: outputvars
        id: vars
        run: |

           $data = (Get-Content ${{matrix.node}}.json) | ConvertFrom-Json
           $secret = $data.secret
           write-host $data.secret
           echo "::set-output name=branch::$secret"
        shell: pwsh

      - name: powershell2
        run: |
           Out-File -FilePath EmptyFile2.txt
           get-childitem
           write-host ${{steps.vars.outputs.branch}}
        shell: pwsh
        
      
      
